### ISSUE TITLE
Improve design of the app

### ISSUE THREAD

**Issue by vaisakhsasikumar** [vaisakhsasikumar/my-electron-app#9]

**Comment by MartynovIvan** [comment]
What so far we can improve:
1. In advanced mode when we have many history items , query result overlap pane "Enter MongoDB Query"

![Image](https://github.com/user-attachments/assets/69797d2d-cc08-42bb-a38e-6e7ef5415ffe)

**Comment by MartynovIvan** [comment]
Also we don't have an option to clean records from history, or remove separate results from it
